/**
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static final String LUA_CODE = ""+
    "function testFun(a, b)\n"+
    "    return a + b\n" + 
    "end";


    public String getGreeting() {
        return LUA_CODE;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Globals globals = createThreadGlobals();

        LuaValue chunk = globals.load(LUA_CODE);
        LuaValue funName = LuaValue.valueOf("testFun");
        LuaValue varArgs = LuaValue.varargsOf(
            LuaValue.valueOf("aarg"),
            LuaValue.valueOf("barg")
        );
        LuaValue retVal = chunk.invokeMethod(funName,varArgs);

        String val = retVal.checkjstring();

        System.out.println(val);

    }

    public static Globals createThreadGlobals(){
        Globals globals = new Globals();
        globals.load(new JseBaseLib());
        globals.load(new PackageLib());
        globals.load(new Bit32Lib());
        globals.load(new TableLib());
        globals.load(new JseStringLib());
        globals.load(new JseMathLib());

        return globals;
    }

}
