/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public record CodeBlob implements ASTPart(
        int lineNumOffset,
        List<String> lines
    ){
        
    }

    public record Comment implements ASTPart(
        int lineNum;
        String line
    ){
    }

    public static interface ASTPart{}


    private record LongDeets(
        int lineNum,
        int level
    ){}
    
    public static List<ASTPart> parseBlockComments(CodeBlob blob){
        List<LongDeets> longOpens = new List<>();
        List<LongDeets> longCloses = new List<>();

        for(int i=0;i<blob.lines.size();i++){
            var line = blob.lines.get(i);
            var idx = line.indexOf("--[");
            if (idx > 0 && line.length() >= idx + 3){
                // start of long block
                int level = 0;
                while(true){
                    int idx2 = idx + level + 3;
                    if(idx2 < line.length()){
                        if(line.charAt(idx2) == '='){
                            level++;
                            continue;
                        }
                        if(line.charAt(idx2) == '['){
                            longOpens.add(new LongDeets(idx+blob.lineNumOffset));
                            break;
                        }
                    } else {
                    }

                }
            }
        }
        
    }
}
